microlinkhq/keyvhq

README.md, packages/keyv-mongo/src/index.js, packages/keyv-redis/package.json, packages/keyv-redis/src/index.js, packages/keyv-sql/src/index.js, packages/keyv-test-suite/src/api.js, packages/keyv-test-suite/src/index.js, packages/keyv-test-suite/src/namespace.js, packages/keyv/package.json, packages/keyv/src/index.js, packages/keyv/test/keyv.js
Closes #11 
Full API docs is to be done with [Nextra](https://nextra.vercel.app/docs/get-started), this just updates all remnants from lukechilds keyv to the new ones in @keyvhq's :)
=> Update readme, remove `keyv` references

packages/core/src/index.js
related:
https://github.com/microlinkhq/keyv/issues/6#issuecomment-826070498
=> chore: exit early if value is undefined

README.md
Missing comma and extra space.
=> Fix syntax error in docs

packages/core/src/index.js, packages/redis/src/index.js, packages/test-suite/src/api.js, packages/test-suite/src/iteration.js
error from stores get bubbled to keyv check, expiry check and namespace check for iterators
=> test: added tests

README.md
=> Docs-notice-update

packages/core/src/index.d.ts, packages/core/test/keyv.test-d.ts, packages/mongo/src/index.d.ts, packages/mysql/src/index.d.ts, packages/postgres/src/index.d.ts, packages/redis/src/index.d.ts, packages/sqlite/src/index.d.ts
=> Typings has

packages/core/test/key.js
This PR is to clarify what is considered a valid key.
Since `has` method just check `undefined` as invalid:
https://github.com/microlinkhq/keyv/blob/master/packages/core/src/index.js#L92
Any other value there should be considered valid.
We can use https://github.com/minimaxir/big-list-of-naughty-strings to checking for more possible key values.
=> test: add key cases

packages/sql/package.json, packages/sql/src/index.js, packages/sql/test/index.js
=> chore: use sql-ts

packages/compress/package.json, packages/core/package.json, packages/memoize/package.json, packages/mongo/package.json, packages/multi/package.json, packages/mysql/package.json, packages/offline/package.json, packages/postgres/package.json, packages/redis/package.json, packages/sql/package.json, packages/sqlite/package.json
=> test: lock ava to 3

packages/compress/package.json, packages/core/package.json, packages/memoize/package.json, packages/mongo/package.json, packages/multi/package.json, packages/mysql/package.json, packages/offline/package.json, packages/postgres/package.json, packages/redis/package.json, packages/sql/package.json, packages/sqlite/package.json
=> test: lock ava to 3 (#84)

packages/postgres/README.md
Beginners may be confused by this error:
Error: connect ECONNREFUSED 127.0.0.1:5432
=> Beginner friendly

.github/dependabot.yml, CHANGELOG.md, docs/css/style.css, index.html, package.json, packages/compress/CHANGELOG.md, packages/compress/README.md, packages/core/CHANGELOG.md, packages/core/src/index.d.ts, packages/core/src/index.js, packages/core/test/keyv.test-d.ts, packages/mongo/src/index.d.ts, packages/mongo/test/mongo.test-d.ts, packages/mysql/src/index.d.ts, packages/mysql/test/mysql.test-d.ts, packages/postgres/src/index.d.ts, packages/postgres/test/postgres.test-d.ts, packages/redis/src/index.d.ts, packages/redis/test/redis.test-d.ts, packages/sql/src/index.js, packages/sqlite/src/index.d.ts, packages/sqlite/test/sqlite.test-d.ts, tsconfig.json
To lint the .d.ts files this change is necessary
=> Changed linter from standard to standard-ts

packages/sql/package.json, packages/sql/test/index.js, packages/sqlite/package.json, packages/sqlite/src/index.js
=> build(deps): change sqlite3 to vscode version

packages/multi/package.json, packages/multi/src/index.js, packages/multi/test/index.js
The `keyv.deserialize` is an async API, so need to wait it
=> fix(multi): wait deserialize promise

packages/core/src/index.js
Unfortunately, I didn't find a way to verify the change with a test.
=> fix(core): wait deserialize promise

packages/core/src/index.d.ts
Current types only allow sync functions.
=> fix: added async deserialize/serialize function types

packages/mysql/src/index.js
=> fix: use mysql pool instead of connection

packages/redis/package.json
=> Revert "Build(deps): Bump ioredis from 5.1.0 to 5.2.0"

README.md, packages/memoize/README.md, packages/mongo/README.md, packages/mysql/README.md, packages/postgres/README.md, packages/redis/README.md, packages/redis/src/index.js, packages/redis/test/index.js, packages/sql/src/index.js, packages/sqlite/README.md
=> test(redis): a better setup for reusing instances

packages/memoize/package.json, packages/memoize/src/index.d.ts
=> feat: memoize: add typescript definition

README.md
=> TTL docfix
